// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/google/wire"
	"school/internal/biz"
	"school/internal/data"
	"school/internal/service"
)

// Injectors from wire.go:

func InitApp() *App {
	user := data.NewUser()
	bizUser := biz.NewUser(user)
	schoolSchool := school.NewSchool(bizUser)
	app := NewApp(schoolSchool)
	return app
}

// wire.go:

var Set = wire.NewSet(data.NewUser, wire.Bind(new(biz.UserPO), new(*data.User)), biz.NewUser, wire.Bind(new(school.UserBiz), new(*biz.User)), school.NewSchool)
